/**
 * The capability checklist for window-algebra, and which example page
 * exercises each item. The hub page (index.html) renders this as a matrix.
 */

const items = (group, list) => list.map(([id, label]) => ({ group, id, label: label ?? id }));

export const CHECKLIST = [
  ...items("Primitives", [
    ["view"], ["row"], ["column"], ["grid"], ["stack"], ["overlay"],
    ["place"], ["size"], ["gap"], ["inset"], ["anchor"],
    ["container/modifier", "generic container() / modifier()"],
    ["predicates", "isNode / isContainer / isModifier / isView"],
    ["kinds", "NODE_KINDS / CONTAINER_KINDS / MODIFIER_KINDS"],
    ["validate"], ["fromJSON"],
  ]),
  ...items("Transforms", [
    ["mirror"], ["flip"], ["rotate"], ["reverse"], ["mapViews"], ["replace"], ["remove"], ["swap"],
    ["transform"], ["walk"], ["fold"], ["views"], ["find"], ["count"], ["equals"],
  ]),
  ...items("Layout modifiers", [
    ["modifiers-registry", "MODIFIERS registry (parallel to LAYOUTS, overridable the same way)"],
    ["withModifiers", "withModifiers(interpreter, mods) combinator"],
    ["mod-smart-gaps", "smart-gaps modifier: no gap/inset with one tiled window"],
    ["mod-no-gaps", "no-gaps modifier: never gap/inset the tiled base"],
    ["mod-mirror", "mirror modifier (xmonad Mirror: transpose rows/columns)"],
    ["mod-reflect-x", "reflect-x modifier (flip left-right)"],
    ["mod-reflect-y", "reflect-y modifier (flip top-bottom)"],
    ["mod-max-windows", "max-windows(n) modifier: overflow windows share a hidden stack slot"],
    ["mod-drop-agreement", "drop interpreters remapped for mirror/reflect-x/reflect-y (applyModifiersToOps)"],
  ]),
  ...items("Derived layouts", [
    ["masterStack"], ["columns"], ["rows"], ["monocle"], ["tabs"], ["autoGrid"], ["fixedGrid"], ["spiral"],
    ["bsp", "BSP (stateful, in workspace state)"],
    ["bsp-fns", "bspLeaf / bspSplit / bspInsert / bspRemove / bspSetRatio / bspRotate / bspIds / bspFrom / bspToLayout"],
    ["floating-layout", "floating layout type (everything floats)"],
    ["floating"], ["centered"], ["dock"], ["hybrid"],
    ["custom-layout", "custom layout interpreters (derive layouts option)"],
    ["drops-registry", "drop interpreters: DROPS / orderDrops / createDropHandler (manager drops option)"],
    ["split-sizing", "persisted split sizes: spec.sizes (columns/rows), spec.ratio (master-stack), tree.ratio (bsp), spec.ratios (spiral)"],
    ["bsp-path-fns", "bspNodeAt / bspSetRatioAt: general L/R-path split addressing"],
    ["tree", "docking tree layout (stateful, in workspace state): i3/Dockview-style row/column/tabs containers"],
    ["tree-fns", "treeIds / treeReconcile / treeRemove / treeSwap / treeSplit / treeAddTab / treeInsertTab / treeParentType / treeFrom / treeFromBsp / treeToLayout"],
    ["tree-path-fns", "treeNodeAt / treeSetSizesAt: comma-joined index-path addressing for layout/resize-split"],
    ["tree-drop-zones", "docking tree drop zones: edges split, center tabs (or swaps), a tab strip reorders/inserts at index"],
  ]),
  ...items("Commands", [
    ["window/create"], ["window/close"], ["window/focus"], ["window/blur"], ["focus/next"], ["focus/previous"],
    ["window/raise"], ["window/lower"], ["window/set-layer"], ["window/move"], ["window/resize"], ["window/set-mode"],
    ["window/toggle-floating"], ["window/minimize"], ["window/maximize"], ["window/fullscreen"], ["window/restore"],
    ["window/set-title"], ["window/set-constraints"], ["window/swap"], ["window/promote"], ["window/move-to-workspace"],
    ["workspace/create"], ["workspace/activate"], ["workspace/remove"],
    ["output/create"], ["output/remove"], ["output/focus"], ["workspace/move-to-output"],
    ["layout/set"], ["layout/set-ratio"], ["layout/rotate-split"], ["layout/resize-split"], ["layout/toggle", "layout/toggle (xmonad ToggleLayouts)"],
    ["layout/to-tree", "layout/to-tree: convert the current layout into a docking tree"], ["config/set"],
    ["window/drop"], ["window/swap-next"], ["window/swap-previous"], ["window/move-before"], ["window/move-after"], ["window/set-draggable"], ["window/detach"],
    ["rules/set"],
    ["window/to-scratchpad"], ["scratchpad/toggle"], ["window/set-sticky"],
    ["window/set-urgent"], ["focus/urgent"],
    ["window/toggle-maximize"], ["window/toggle-fullscreen"], ["window/toggle-sticky"], ["window/from-scratchpad"],
    ["workspace/rename"], ["workspace/reorder"], ["output/reorder"],
    ["window/pop-out", "window/pop-out: leave the layout for a separate browser window"],
    ["window/pop-in", "window/pop-in: reverse of window/pop-out"],
    ["extensions", "custom command handlers (extensions)"],
  ]),
  ...items("Rejections", [
    ["missing-id"], ["duplicate-id"], ["unknown-parent"], ["unknown-workspace"], ["unknown-window"], ["unknown-layer"],
    ["unknown-mode"], ["different-workspaces"], ["last-workspace"], ["invalid-layout"], ["unknown-layout", "unknown-layout (manager)"], ["invalid-ratio"], ["not-bsp"],
    ["unknown-command"], ["invalid-command"],
    ["same-window"], ["unknown-zone"], ["not-tiled"], ["blocked"], ["drag-disabled"], ["not-draggable"], ["zone-disabled"], ["too-small"], ["invalid-config"],
    ["invalid-rules"],
    ["not-scratchpad"], ["empty-scratchpad"], ["invalid-sticky"], ["not-on-workspace"],
    ["invalid-urgent"], ["no-urgent-window"],
    ["handler-threw", "an extension handler that throws becomes a handler-threw rejection"],
    ["invalid-geometry"], ["invalid-constraints"], ["not-resizable"],
    ["popup-blocked", "attachPopouts rejects (with an event) when window.open is blocked"],
    ["last-output", "output/remove: can't remove the only output"],
    ["last-workspace-on-output", "workspace/remove or workspace/move-to-output: an output always keeps ≥1 workspace"],
    ["missing-workspaces", "output/create: workspaces: [] is rejected"],
    ["future-version", "load() refuses a state newer than STATE_VERSION"],
    ["resize-split-invalid", "layout/resize-split validation: not-resizable, invalid-path, unknown-split, invalid-weights, missing-value, missing-weights"],
  ]),
  ...items("Policies", [
    ["focus-raises", "focus vs raise (config.focusRaises)"],
    ["layers", "7 stacking layers"],
    ["modal-graph", "modal graph: nested modals, focus redirection"],
    ["blocked-inert", "blocked windows: inert contents, clicks redirect to the modal"],
    ["cascade-close", "close cascades to child windows"],
    ["refocus", "refocus from focus history"],
    ["focus-restores", "focus restores a minimized window / switches workspace"],
    ["roles", "roles: dialog, sheet, popover, menu, tooltip, panel, notification"],
    ["requested-actual", "requested vs actual geometry"],
    ["tiled-constraints", "constraints honoured for tiled windows"],
    ["gap-inset-config", "config gap / inset"],
    ["projections", "duplicate views become projections"],
    ["drop-semantics", "tiled drops: center swaps, edges insert (BSP: split), per layout axis"],
    ["drag-settings", "config.drag: tiled mode, edgeZone, preview, tooSmall; per-layout drag override"],
    ["pinned", "pinned windows (draggable: false)"],
    ["window-rules", "declarative window rules: config.rules, matched at window/create, explicit fields win"],
    ["scratchpad", "i3-style scratchpad: hide a window off every workspace, toggle it back floating and centered"],
    ["sticky", "EWMH sticky windows: visible on every workspace, keep their stacking"],
    ["urgency", "urgency hints (EWMH/X11-style): config.urgency.clearOnFocus, focus/urgent picks the oldest urgent window"],
    ["tiled-aspect-ratio", "exact constraints.aspectRatio becomes CSS aspect-ratio for tiled windows"],
    ["popped-out", "popped-out: pop-out leaves the layout like minimized, but stays 'visible elsewhere' (isVisible/isBlocked, queries)"],
  ]),
  ...items("Events & effects", [
    ["events", "all event types rendered"],
    ["effect-render", "render effect"],
    ["effect-focus", "WM focus ↔ keyboard focus (attachInput subscribe, focusin)"],
    ["subscribe"],
    ["window/urgent-changed"],
  ]),
  ...items("State & history", [
    ["createState"], ["createWorkspace"], ["createWindowRecord"],
    ["constants", "LAYERS / ROLES / STATUSES / DEFAULT_CONFIG / COMMANDS / LAYOUTS"],
    ["update"], ["reduce"], ["replay"], ["derive"], ["presentationContext"],
    ["queries", "queries (focusable, modalTarget, stackingOrder, …)"],
    ["matchRules", "matchRules(state, window) — pure rule-matching query"],
    ["undo-redo", "undo / redo (manager)"],
    ["history-fns", "createHistory / record / undo / redo / canUndo / canRedo"],
    ["serialize", "serialize / load"],
    ["log-replay", "command log + replay from log"],
    ["version", "STATE_VERSION stamped on every state, incl. serialize()"],
    ["migrate", "migrate(state): upgrades older states through MIGRATIONS"],
  ]),
  ...items("Outputs", [
    ["outputs-state", "state.outputs (id → { workspaces, activeWorkspace }), outputOrder, focusedOutput; activeWorkspace mirrors the focused output"],
    ["output-queries", "outputsList / outputActiveWorkspace / outputOf / workspacesOf / focusedOutput queries"],
    ["per-output-visibility", "isVisible / visibleWindows / focusable / paintOrder resolve per output, independent of which one is focused"],
    ["derive-per-output", "derive(state, { output }): derives an output's own active workspace"],
    ["multi-renderer", "wm.setRenderer(outputId, renderer): one renderer (and measureOutput) per output, driving several stages at once"],
    ["focus-crosses-outputs", "window/focus and focus/next / focus/previous cross outputs, focusing the one a target window lives on"],
    ["migrate-v1-to-v2", "migrate(): a pre-outputs (version 1) state is backfilled with a single default output holding every workspace"],
  ]),
  ...items("CSS compiler", [
    ["compile"], ["toHTML"], ["styleText"], ["tracks"], ["px"], ["anchorName"], ["BASE_CSS"],
    ["flex-weights", "flex weights"], ["grid-tracks", "grid tracks & areas"],
    ["anchor-css", "CSS anchor positioning"], ["container-queries", "container queries in views"],
    ["anchor-positioner-css", "flip → position-try-fallbacks (flip-block/flip-inline); gravity → position-area"],
    ["stack-inert", "stack: inactive children hidden + inert"],
    ["splitter-render", "compiled [data-wm-splitter] handles: role, aria-orientation, aria-valuenow, data-wm-path/index/count"],
  ]),
  ...items("Browser", [
    ["createDomRenderer"], ["keyed-dom", "keyed reconcile keeps elements"],
    ["measure", "measure() actual geometry"], ["elementFor"], ["styleOf"], ["destroy"],
    ["anchor-fallback", "JS anchor fallback (forced)"],
    ["anchor-positioner-fallback", "JS fallback: flip/slide/resize/gravity constraint adjustment via positionPopup"],
    ["attachInput"], ["drag-move", "drag to move"], ["resize-edges", "resize from all 8 edges"],
    ["command-buttons", "data-wm-command buttons"],
    ["tiled-drag", "drag tiled windows by the title bar (threshold, one window/drop)"],
    ["drag-preview", "drag preview: ghost of the next layout + drop-zone highlight"],
    ["drag-shield", "iframe shield during drags"], ["drag-cancel", "Esc / pointercancel aborts a drag"],
    ["drag-undo", "one undo step (and one log entry) per drag"],
    ["drag-to-float", "drag a tiled window out as floating (modifier / threshold)"],
    ["float-to-tile", "drop a floating window into the layout"],
    ["cross-workspace", "drop onto a workspace target (data-wm-workspace-target), optional follow"],
    ["tab-reorder", "drag tabs to reorder the tab strip"],
    ["drag-children", "dialogs / popovers travel with their dragged parent"],
    ["touch-longpress", "touch: long-press to drag; content keeps scrolling"],
    ["a11y-announce", "aria-live drag announcements (announce option)"],
    ["keyboard-moves", "keyboard moving of the focused window (keyboard option)"], ["tab-buttons", "tab chrome buttons"], ["snap", "snap to grid"],
    ["snap-zones", "Windows-Snap-style half/quarter/maximize preview while dragging a floating window near a stage edge or corner (config.snap.edges/threshold/zones)"],
    ["magnetize", "magnetism: floating move/resize snaps to other visible windows' edges and the stage (config.snap.magnet)"],
    ["splitter-drag", "drag a splitter to resize (pointer capture, min/max constraints, one undo step)"],
    ["splitter-keyboard", "focus a splitter and press the arrow key along its axis (splitterStep option)"],
    ["htmlSurface"], ["lazySurface"], ["iframeSurface"], ["canvasSurface"], ["createSurfaceRegistry"],
    ["state-preserving", "surfaces keep mounted state across layouts"],
    ["createFrameScheduler"], ["immediateScheduler"],
    ["animate", "createDomRenderer({ animate }): layout changes run inside document.startViewTransition, off by default"],
    ["animate-names", "unique, sanitized view-transition-name per primary view (setAnimate toggles it live)"],
    ["animate-gesture-immediate", "drag/resize gestures (and an explicit immediate commit) never animate"],
    ["animate-reduced-motion", "prefers-reduced-motion: reduce (and unsupported browsers) make animate a no-op"],
    ["attachPopouts", "GoldenLayout/Dockview-style pop-out: opens a real browser window, adopts the view's DOM into it (renderer release/adopt), syncs title and focus, pops back in when the popup closes or on window/pop-in"],
  ]),
  ...items("Manager & geometry", [
    ["createWindowManager"], ["present", "wm.present()"], ["keyboard", "keyboard shortcuts"],
    ["rect-helpers", "geometry: rect / intersects / intersection / union / clamp / inset / constrainSize …"],
    ["drag-fns", "createDrag / updateDrag / createResize / updateResize / EDGES"],
    ["drop-fns", "dropZoneAt / dropTargetAt / previewDrop / zoneRect"],
    ["snap-fns", "snapZoneAt / snapZoneRect / magnetize / magnetizeResize (pure)"],
    ["updateRatio", "updateRatio (divider drag)"],
    ["size-hints", "constrainSize honours aspectRatio, widthIncrement/heightIncrement, baseWidth/baseHeight; sizeToCells"],
    ["positionPopup", "positionPopup(anchorRect, popupSize, stage, options): pure xdg_positioner-style placement"],
    ["positioner-flip", "flip: side/gravity (primary axis) or align (cross axis) flips to its opposite"],
    ["positioner-slide", "slide: translates back into the stage without resizing"],
    ["positioner-resize", "resize: shrinks to fit the stage, anchored edge held fixed"],
    ["positioner-gravity", "gravity: which way the popup grows from its attach point, independent of side"],
  ]),
  ...items("Accessibility", [
    ["aria-window", "windows as labelled regions: role=group, aria-label = title"],
    ["aria-dialog", "role=dialog for dialog/sheet windows, aria-modal=true when modal"],
    ["aria-tabpanel", "tab strip role=tablist/tab (aria-selected, aria-controls) ↔ panel role=tabpanel (aria-labelledby); tabId/panelId"],
    ["f6-cycle", "F6 / Shift+F6 cycles WM focus between windows (attachInput keyboard option)"],
    ["focus-trap", "Tab is trapped inside the focused window while it is modal (wraps at the ends)"],
    ["reduced-motion", "chrome transitions gated by @media (prefers-reduced-motion: no-preference)"],
  ]),
  ...items("Theming", [
    ["theme-tokens", "THEME_TOKENS / THEME_CSS: the --wa-* custom properties (colours, radii, spacing, focus ring, splitter, title bar, shadows), light and dark defaults, prefers-contrast: more"],
    ["theme-override", "override any token on :root (or an ancestor of one stage); defaults have zero specificity"],
    ["rules-css", "RULES_CSS / BASE_CSS = THEME_CSS + the rules: no literal colour, length or shadow"],
  ]),
  ...items("Touch and pen", [
    ["touch-option", "attachInput({ touch }): opt-in; sets data-wm-touch, which BASE_CSS maps to the touch-action each gesture needs"],
    ["touch-pinch", "pinch: two touches on a floating window resize it (one gesture, honours constraints); createPinch / updatePinch"],
    ["touch-swipe-tabs", "swipe a tab strip left/right to switch tabs (touch or pen); swipeOf"],
    ["touch-swipe-workspaces", "two-finger horizontal swipe switches workspace"],
    ["touch-context", "long-press a window: wm-contextmenu event / callback / command; the native menu is suppressed"],
  ]),
  ...items("Cross-tab sync", [
    ["attachSync", "attachSync({ wm, channel }): opt-in BroadcastChannel sync of versioned state snapshots, last-writer-wins by Lamport clock"],
    ["sync-conflicts", "concurrent edits in two tabs converge on one winner (clock, then tab id); undo/redo sync like any change"],
    ["sync-popouts", "pop-outs stay in the tab that opened them: peers see the window minimized and never open a popup"],
  ]),
  ...items("Framework bindings", [
    ["createReactBindings", "createReactBindings(React) → { useWindowManager, useWindowState, WindowManagerStage }"],
    ["useWindowManager", "useWindowManager(options): creates a wm once, subscribes via useSyncExternalStore"],
    ["useWindowState", "useWindowState(wm, selector): subscribes to a derived slice of state"],
    ["WindowManagerStage", "WindowManagerStage: mounts createDomRenderer + attachInput into a ref'd host"],
    ["react-portal-surfaces", "renderSurface + createPortal: window content as ordinary React trees, mounted as portals"],
    ["defineWindowAlgebraElement", "defineWindowAlgebraElement(name): a framework-agnostic <wa-stage> custom element"],
    ["attachStage", "attachStage(host, options): the element's reusable DOM-shaped core (wm + renderer + input)"],
    ["wa-stage-configure", "<wa-stage>.configure(options) / .wm: set or swap the manager live, read it back"],
    ["bindings-exports", "package.json exports subpaths ./react and ./element"],
  ]),
];

export const PAGES = [
  {
    href: "./playground.html",
    short: "Playground",
    title: "Layout-algebra playground",
    blurb: "Edit a layout tree as JSON or with constructors, apply every transform, and read the compiled CSS beside a live preview.",
    covers: [
      "view", "row", "column", "grid", "stack", "overlay", "place", "size", "gap", "inset", "anchor",
      "container/modifier", "predicates", "kinds", "validate", "fromJSON",
      "mirror", "flip", "rotate", "reverse", "mapViews", "replace", "remove", "swap", "transform", "walk", "fold", "views", "find", "count", "equals",
      "masterStack", "columns", "rows", "monocle", "tabs", "autoGrid", "fixedGrid", "spiral", "bsp-fns", "floating", "centered", "dock", "hybrid",
      "compile", "toHTML", "styleText", "tracks", "px", "anchorName", "BASE_CSS", "flex-weights", "grid-tracks", "anchor-css", "stack-inert",
      "projections", "createDomRenderer", "keyed-dom", "styleOf", "elementFor", "lazySurface", "container-queries",
    ],
  },
  {
    href: "./layouts.html",
    short: "Layouts",
    title: "Derived-layout gallery",
    blurb: "Every derived layout, switchable live, plus small multiples of all of them at once. Add, remove, swap and promote windows; drag dividers.",
    covers: [
      "masterStack", "columns", "rows", "monocle", "tabs", "autoGrid", "fixedGrid", "spiral", "bsp", "bsp-fns", "floating-layout", "custom-layout",
      "dock", "centered", "hybrid",
      "window/create", "window/close", "window/promote", "focus/next", "focus/previous", "layout/set", "layout/set-ratio", "layout/rotate-split",
      "config/set", "gap-inset-config", "derive", "compile", "toHTML", "present", "updateRatio", "tab-buttons", "createFrameScheduler",
      "createWindowManager", "attachInput", "createDomRenderer", "createSurfaceRegistry", "lazySurface", "keyboard", "flex-weights", "grid-tracks",
      "stack-inert", "not-bsp",
      "window/drop", "window/swap-next", "window/swap-previous", "window/move-before", "window/move-after", "drop-semantics", "drag-settings",
      "tiled-drag", "drag-preview", "drag-cancel", "drag-undo", "drops-registry", "drop-fns",
      "tab-reorder", "keyboard-moves", "a11y-announce", "drag-to-float", "float-to-tile", "touch-longpress",
      "layout/resize-split", "split-sizing", "bsp-path-fns", "splitter-render", "splitter-drag", "splitter-keyboard", "resize-split-invalid",
      "modifiers-registry", "withModifiers", "mod-smart-gaps", "mod-no-gaps", "mod-mirror", "mod-reflect-x", "mod-reflect-y", "mod-max-windows",
      "mod-drop-agreement", "layout/toggle",
      "tree", "tree-fns", "tree-path-fns", "tree-drop-zones", "layout/to-tree",
      "animate", "animate-names", "animate-gesture-immediate", "animate-reduced-motion",
    ],
  },
  {
    href: "./desktop.html",
    short: "Desktop",
    title: "Tiling desktop",
    blurb: "Workspaces, floating and tiled windows, dock panels, 7 stacking layers, focus-vs-raise, nested modals with focus redirection, every role, and keyboard shortcuts.",
    covers: [
      "window/create", "window/close", "window/focus", "window/blur", "focus/next", "focus/previous", "window/raise", "window/lower", "window/set-layer",
      "window/move", "window/resize", "window/toggle-floating", "window/minimize", "window/maximize", "window/fullscreen", "window/restore",
      "window/set-title", "window/move-to-workspace", "window/promote", "workspace/create", "workspace/activate", "workspace/remove", "layout/set", "config/set",
      "window/pop-out", "window/pop-in", "popped-out", "attachPopouts", "popup-blocked",
      "focus-raises", "layers", "modal-graph", "blocked-inert", "cascade-close", "refocus", "focus-restores", "roles", "gap-inset-config",
      "queries", "effect-focus", "subscribe", "keyboard", "drag-move", "resize-edges", "command-buttons", "snap", "anchor-css", "custom-layout", "dock",
      "snap-zones", "magnetize", "snap-fns",
      "anchor-positioner-css", "positioner-flip", "positioner-slide",
      "createWindowManager", "attachInput", "createDomRenderer", "createFrameScheduler", "createSurfaceRegistry", "lazySurface", "undo-redo", "tab-buttons",
      "window/drop", "window/swap-next", "window/swap-previous", "window/move-before", "window/move-after", "window/set-draggable",
      "drop-semantics", "drag-settings", "pinned", "tiled-drag", "drag-preview", "drag-shield", "drag-cancel", "drag-undo",
      "window/detach", "drag-to-float", "float-to-tile", "cross-workspace", "drag-children", "a11y-announce", "touch-longpress",
      "rules/set", "window-rules", "matchRules", "invalid-rules",
      "window/to-scratchpad", "scratchpad/toggle", "window/set-sticky", "scratchpad", "sticky", "not-scratchpad", "empty-scratchpad", "invalid-sticky",
      "window/set-urgent", "focus/urgent", "urgency", "window/urgent-changed", "invalid-urgent", "no-urgent-window",
      "layout/resize-split", "split-sizing", "splitter-render", "splitter-drag", "splitter-keyboard",
      "tree", "tree-fns", "tree-path-fns", "tree-drop-zones", "layout/to-tree",
      "aria-window", "aria-dialog", "aria-tabpanel", "f6-cycle", "focus-trap", "reduced-motion",
      "animate", "animate-names", "animate-gesture-immediate", "animate-reduced-motion",
    ],
  },
  {
    href: "./console.html",
    short: "Console",
    title: "Command console",
    blurb: "Issue any of the 58 built-in commands (or broken ones), watch every event and effect, time-travel with undo/redo and a replay scrubber, serialize and restore.",
    covers: [
      ...[
        "window/create", "window/close", "window/focus", "window/blur", "focus/next", "focus/previous", "window/raise", "window/lower", "window/set-layer",
        "window/move", "window/resize", "window/set-mode", "window/toggle-floating", "window/minimize", "window/maximize", "window/fullscreen", "window/restore",
        "window/pop-out", "window/pop-in",
        "window/set-title", "window/set-constraints", "window/swap", "window/promote", "window/move-to-workspace", "workspace/create", "workspace/activate",
        "workspace/remove", "output/create", "output/remove", "output/focus", "workspace/move-to-output",
        "layout/set", "layout/set-ratio", "layout/rotate-split", "layout/resize-split", "layout/toggle", "layout/to-tree", "config/set", "extensions",
        "window/drop", "window/swap-next", "window/swap-previous", "window/move-before", "window/move-after", "window/set-draggable", "window/detach",
        "rules/set",
        "window/to-scratchpad", "scratchpad/toggle", "window/set-sticky",
        "window/set-urgent", "focus/urgent",
        "window/toggle-maximize", "window/toggle-fullscreen", "window/toggle-sticky", "window/from-scratchpad", "workspace/rename", "workspace/reorder", "output/reorder",
      ],
      "same-window", "unknown-zone", "not-tiled", "blocked", "drag-disabled", "not-draggable", "zone-disabled", "too-small", "invalid-config",
      "not-scratchpad", "empty-scratchpad", "invalid-sticky", "not-on-workspace",
      "missing-id", "duplicate-id", "unknown-parent", "unknown-workspace", "unknown-window", "unknown-layer", "unknown-mode", "different-workspaces",
      "last-workspace", "invalid-layout", "unknown-layout", "invalid-ratio", "not-bsp", "unknown-command", "invalid-command", "invalid-rules",
      "invalid-urgent", "no-urgent-window", "urgency", "window/urgent-changed", "resize-split-invalid", "popped-out", "handler-threw", "invalid-geometry", "invalid-constraints", "not-resizable",
      "events", "effect-render", "effect-focus", "subscribe", "update", "reduce", "replay", "undo-redo", "history-fns", "serialize", "log-replay",
      "version", "migrate", "future-version",
      "createState", "createWorkspace", "createWindowRecord", "constants", "derive", "presentationContext", "queries", "matchRules", "createWindowManager",
      "compile", "createDomRenderer", "immediateScheduler", "equals", "cascade-close", "modal-graph", "refocus", "window-rules",
    ],
  },
  {
    href: "./surfaces.html",
    short: "Surfaces",
    title: "Surfaces",
    blurb: "html, lazy, iframe (srcdoc) and canvas surfaces keep their mounted state while windows travel through layouts; a mount/unmount log shows the lifecycle.",
    covers: [
      "htmlSurface", "lazySurface", "iframeSurface", "canvasSurface", "createSurfaceRegistry", "state-preserving", "keyed-dom", "elementFor",
      "layout/set", "window/swap", "window/toggle-floating", "window/minimize", "window/restore", "window/fullscreen", "window/focus",
      "createDomRenderer", "createFrameScheduler", "createWindowManager", "attachInput", "tabs", "bsp", "masterStack", "spiral", "monocle",
    ],
  },
  {
    href: "./geometry.html",
    short: "Geometry",
    title: "Requested vs actual geometry",
    blurb: "Requested placements drawn against measured rectangles, constraints on tiled windows, container-query responsive content, anchors with the JS fallback forced, and geometry helpers.",
    covers: [
      "requested-actual", "tiled-constraints", "measure", "window/move", "window/resize", "window/set-constraints", "container-queries",
      "anchor-css", "anchor-fallback", "anchor", "anchorName", "rect-helpers", "drag-fns", "snap", "createFrameScheduler",
      "drag-move", "resize-edges", "roles", "styleOf", "createDomRenderer", "destroy", "createWindowManager", "attachInput", "px",
      "window/toggle-floating", "size-hints", "tiled-aspect-ratio",
      "anchor-positioner-css", "anchor-positioner-fallback", "positionPopup", "positioner-flip", "positioner-slide",
      "positioner-resize", "positioner-gravity",
    ],
  },
  {
    href: "./ide.html",
    short: "IDE",
    title: "IDE workspace (app)",
    blurb: "A realistic app: file tree, editor tabs, terminal, live preview iframe, command palette, context menus, toasts, problems panel, three workspaces, and session persistence.",
    covers: [
      "custom-layout", "grid-tracks", "stack-inert", "roles", "keyboard", "serialize", "undo-redo", "version", "migrate",
      "workspace/activate", "window/create", "window/close", "window/focus", "window/set-title", "window/toggle-floating", "window/maximize", "window/restore",
      "layout/set", "layout/set-ratio", "config/set", "iframeSurface", "lazySurface", "canvasSurface", "state-preserving", "effect-focus",
      "createWindowManager", "attachInput", "createDomRenderer", "createFrameScheduler", "container-queries", "updateRatio", "extensions",
      "window/move-to-workspace", "focus-restores", "subscribe",
    ],
  },
  {
    href: "./basic.html",
    short: "Basic",
    title: "Quick start",
    blurb: "The original minimal demo: a handful of windows, a layout switcher, undo/redo. The shortest path through the API.",
    covers: ["createWindowManager", "attachInput", "lazySurface", "layout/set", "layout/set-ratio", "window/toggle-floating", "undo-redo", "focus/next", "modal-graph"],
  },
  {
    href: "./outputs.html",
    short: "Outputs",
    title: "Multiple outputs",
    blurb: "sway-style outputs: two stages side by side, each with its own workspaces and renderer. Move workspaces between outputs, focus either one, and watch focus/next cross both.",
    covers: [
      "output/create", "output/remove", "output/focus", "workspace/move-to-output",
      "last-output", "last-workspace-on-output", "missing-workspaces",
      "outputs-state", "output-queries", "per-output-visibility", "derive-per-output", "multi-renderer", "focus-crosses-outputs", "migrate-v1-to-v2",
      "window/create", "window/close", "window/toggle-floating", "focus/next", "workspace/create", "workspace/activate",
      "createWindowManager", "attachInput", "createDomRenderer", "createFrameScheduler", "createSurfaceRegistry",
      "present", "derive", "subscribe",
    ],
  },
  {
    href: "./element.html",
    short: "wa-stage",
    title: "<wa-stage> custom element",
    blurb: "A framework-agnostic custom element that owns its own manager, DOM renderer and input adapter, exposing the live manager as `.wm`. Works fully offline.",
    covers: [
      "defineWindowAlgebraElement", "attachStage", "wa-stage-configure", "bindings-exports",
      "createWindowManager", "createSurfaceRegistry", "lazySurface", "layout/set", "window/close", "undo-redo",
      "window/create", "focus/next",
    ],
  },
  {
    href: "./theming.html",
    short: "Theming",
    title: "Theming tokens",
    blurb: "Every colour, radius, spacing, focus ring, splitter, title bar and shadow in the library's CSS is a --wa-* token. Switch scheme, simulate high contrast, override tokens live.",
    covers: [
      "theme-tokens", "theme-override", "rules-css", "BASE_CSS", "createWindowManager", "attachInput", "createDomRenderer", "createFrameScheduler", "createSurfaceRegistry",
      "lazySurface", "layout/set", "window/focus", "splitter-render", "tab-buttons", "drag-preview",
    ],
  },
  {
    href: "./touch.html",
    short: "Touch",
    title: "Touch and pen gestures",
    blurb: "Pinch a floating window, swipe the tab strip, two-finger swipe between workspaces, long-press for a menu. Opt-in through attachInput({ touch }).",
    covers: [
      "touch-option", "touch-pinch", "touch-swipe-tabs", "touch-swipe-workspaces", "touch-context", "touch-longpress", "drag-move", "tiled-drag", "keyboard",
      "createWindowManager", "attachInput", "createDomRenderer", "createFrameScheduler", "createSurfaceRegistry", "workspace/activate", "window/resize", "window/focus",
      "window/toggle-floating", "window/maximize", "window/minimize", "window/close", "undo-redo", "subscribe",
    ],
  },
  {
    href: "./sync.html",
    short: "Sync",
    title: "Cross-tab sync",
    blurb: "Open the page in two tabs: window changes, undo and redo are shared over a BroadcastChannel, with a Lamport-clock status line and a log of what was sent, applied or ignored.",
    covers: [
      "attachSync", "sync-conflicts", "sync-popouts", "createWindowManager", "attachInput", "createDomRenderer", "createFrameScheduler",
      "window/create", "window/close", "window/toggle-floating", "layout/set", "undo-redo", "subscribe",
    ],
  },
  {
    href: "./react.html",
    short: "React",
    title: "React bindings",
    blurb: "createReactBindings(React): useWindowManager, useWindowState, and WindowManagerStage rendering window content as React portals. Loads React from esm.sh — needs network.",
    covers: [
      "createReactBindings", "useWindowManager", "useWindowState", "WindowManagerStage", "react-portal-surfaces", "bindings-exports",
      "createWindowManager", "layout/set", "window/close", "window/create", "undo-redo", "subscribe",
    ],
  },
];
